// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-rv5A0SoGIfDC1zoTxTDOAoWHz3k-dXw',
    appId: '1:832632525898:android:1591688f3cbd9a26a5c2b3',
    messagingSenderId: '832632525898',
    projectId: 'symphonicdiagnosis',
    storageBucket: 'symphonicdiagnosis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQAKgGVSoZTk7Cl89QX4dybMujfWpX5Y',
    appId: '1:832632525898:ios:3b463da9dfb09acea5c2b3',
    messagingSenderId: '832632525898',
    projectId: 'symphonicdiagnosis',
    storageBucket: 'symphonicdiagnosis.appspot.com',
    androidClientId: '832632525898-lvhbla3bhtsecdu0vri7pu4uma3papai.apps.googleusercontent.com',
    iosClientId: '832632525898-r61tgrppu8pu9s94j1573lvjn3rathn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.symphonicdiagnosis',
  );
}
